### PR TITLE
Add the completed data.md file

### PR DESCRIPTION
**Pull request by scpuopolo**
Finished defining the data for the application.

### CODE REVIEW

**Comment by jacksonmacdonald21** [comment]
Maybe we should include 'college' for users?

**Comment by jacksonmacdonald21** [comment]
Rating as well could be added to User and Company data

**Comment by jacksonmacdonald21** [comment]
Also, where should we store the ID for saved listings?

**Comment by jacksonmacdonald21** [comment]
Also, can we have a way to track recently viewed items for both the user and suggestions?

**Comment by scpuopolo** [comment]
I added your suggested data to the file. Let me know if it looks good now.

**Comment by jacksonmacdonald21** [comment]
Looks fantastic 🕺

**Pull request merged**
